
# Required
version: 2

conda:
  environment: environment.yml

# python:
#   install:
#     - requirements: requirements.txt
#     - method: pip
#       path: .
# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
